-- ============================================================
-- Zarada ERP: System Integrity & Health Check Script
-- 🛠️ Generated by: 안욱빈 (Agentic AI)
-- 📅 Date: 2026-01-11
-- 🎯 Purpose: Scan database for anomalies, orphaned records, and security gaps.
-- ============================================================

-- 1. SECURITY CHECK: RLS Status on Critical Tables
SELECT 
    schemaname, 
    tablename, 
    rowsecurity AS rls_enabled 
FROM pg_tables 
WHERE schemaname = 'public' 
ORDER BY rls_enabled ASC; 
-- ⚠️ Expected: All relevant tables should be true (t).

-- 2. INTEGRITY CHECK: Orphaned Profiles (Profile exists, but Auth User deleted)
SELECT 
    p.id, 
    p.email, 
    p.name, 
    'Orphaned Profile (No Auth User)' as issue
FROM user_profiles p
LEFT JOIN auth.users u ON p.id = u.id
WHERE u.id IS NULL;

-- 3. INTEGRITY CHECK: Orphaned Auth Users (Auth User exists, but Profile missing)
SELECT 
    u.id, 
    u.email, 
    'Missing Profile' as issue
FROM auth.users u
LEFT JOIN user_profiles p ON u.id = p.id
WHERE p.id IS NULL;

-- 4. RELATIONSHIP CHECK: Children without valid Parents
SELECT 
    c.id, 
    c.name, 
    c.parent_id, 
    'Child with Invalid Parent ID' as issue
FROM children c
LEFT JOIN user_profiles p ON c.parent_id = p.id
WHERE c.parent_id IS NOT NULL AND p.id IS NULL;

-- 5. RELATIONSHIP CHECK: Schedules with Invalid Child or Therapist
SELECT 
    s.id, 
    s.start_time, 
    'Invalid Child Link' as issue
FROM schedules s
LEFT JOIN children c ON s.child_id = c.id
WHERE s.child_id IS NOT NULL AND c.id IS NULL
UNION ALL
SELECT 
    s.id, 
    s.start_time, 
    'Invalid Therapist Link' as issue
FROM schedules s
LEFT JOIN user_profiles t ON s.therapist_id = t.id
WHERE s.therapist_id IS NOT NULL AND t.id IS NULL;

-- 6. SUPER ADMIN CHECK
SELECT id, email, role, status 
FROM user_profiles 
WHERE role = 'super_admin' OR email = 'anukbin@gmail.com';

-- 7. COLUMN VALIDATION check for 'therapist_id' in children (Should NOT exist or be NULL always)
-- This is just to confirm schema state. If it errors, column doesn't exist (Good).
-- If it runs and returns data, we have ghost column usage.
DO $$ 
BEGIN 
    -- Only run this if column exists to avoid script error
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='children' AND column_name='therapist_id') THEN
        RAISE NOTICE '⚠️ WARNING: therapist_id column exists in children table. Verify if it is used.';
    ELSE
        RAISE NOTICE '✅ OK: therapist_id column correctly absent from children table.';
    END IF;
END $$;
